### ISSUE TITLE
versao variable not initialised

### ISSUE THREAD

**Issue by PVi1** [diegocanton/remove_ubnt_mf#3]
Hi, 
versao was not initialised so fw was not downloaded in my case.
FW was downloaded to /etc/persistent directory

Fix is here:

```
#detect version of fw
 versao=`mca-status  | grep firmware | cut -d, -f3 | cut -d= -f2 | cut -d. -f1`
#move to /tmp
cd /tmp
#then continue as planned
    if [ "$versao" == "XM" ]; then
```

**Comment by diegocanton** [comment]
Download location fixed WGET -O.

Excuse, I not Copy this code of Alexandre, fault me. 

Thanks.

**Comment by diegocanton** [comment]
I need sleep :/
