### ISSUE TITLE
!/bin/bash - no bash on Airmax

### ISSUE THREAD

**Issue by schulti** [diegocanton/remove_ubnt_mf#4]
if I try to run the desinfect script locally on the AirOS device, I get an error because /bin/bash is not installed. Suggesting to globally move to /bin/sh as it will also run locally on the antennas.

**Comment by diegocanton** [comment]
Thanks your support

**Comment by diegocanton** [comment]
What's AirOS Version?

It's tested in 5.5.x or later and OK.

wget of AirOS not support https, you need hosting script in your server HTTP, it's example.

**Comment by schulti** [comment]
Hi,

we use a customized AirOS here at http://funkfeuer.at.

It seems that our version does not include bash - I wasn't aware of that.
But the script works well using /bin/sh.

# 

XM.v5.5.8.0xFF.v29# /bin/bash
-sh: /bin/bash: not found
XM.v5.5.8.0xFF.v29# /bin/sh

BusyBox v1.11.2 (2014-01-05 17:13:22 CET) built-in shell (ash)
Enter 'help' for a list of built-in commands.

XM.v5.5.8.0xFF.v29# exit

# XM.v5.5.8.0xFF.v29#

# Also our XW custom firmware seem to have no bash:

XW.v5.5.9.0xFF.v6# /bin/bash
-sh: /bin/bash: not found
XW.v5.5.9.0xFF.v6# /bin/sh

BusyBox v1.11.2 (2014-04-03 17:57:36 EEST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

XW.v5.5.9.0xFF.v6# exit

# XW.v5.5.9.0xFF.v6#

No need to further investigate this, since it seems to be a proprietary
situation with our custom image.

Thank you!

LgS

2016-05-16 12:50 GMT+02:00 diegocanton notifications@github.com:

**Comment by diegocanton** [comment]
Thanks for your report
